### ISSUE TITLE
【ChatGLM2_VC_SadTalker.ipynb】colab运行notebook视频聊天报错

### ISSUE THREAD

**Issue by LouisHeck** [KevinWang676/ChatGLM2-Voice-Cloning#3]
1. 在colab中运行Notebook，开启服务，正常启动
![1689833010302](https://github.com/KevinWang676/ChatGLM2-Voice-Cloning/assets/38588261/2a559ae5-8546-40b0-9ca0-509b00a35d2f)

2. 上传图片后，点击开始视频聊天，notebook报错如下：

using safetensor as default
{'checkpoint': 'checkpoints/SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config/auido2pose.yaml', 'audio2exp_yaml_path': 'src/config/auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints/mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config/facerender.yaml'}
/tmp/gradio/560de6f36a949315f889c1735e88228be652d56e/image.png
False None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 704, in wrapper
    response = f(*args, **kwargs)
  File "/content/ChatGLM2-SadTalker/src/gradio_demo.py", line 81, in test
    assert use_ref_video == True and ref_info == 'all'
AssertionError

![1689833155869](https://github.com/KevinWang676/ChatGLM2-Voice-Cloning/assets/38588261/50186769-6248-41c8-aafa-cb2016b953f3)

**Comment by LouisHeck** [comment]
> 这个error我还没有遇到过，检查一下是否用了GPU环境，我使用Colab A100是可以正常运行的；更建议Vast AI部署（如果之前用过的话）

我发现，如果没有"克隆专属声音"会报上述错误，如果有，则不报错。
![1689839095855](https://github.com/KevinWang676/ChatGLM2-Voice-Cloning/assets/38588261/0877c6f6-7d15-4bfc-a8fb-ae4e8221fa5e)

**Comment by ZenXir** [comment]
@LouisHeck 你的环境点击 “开始AI声音克隆吧” 可以正常的克隆声音吗？ pip list 环境可以分享下吗？
我的的一点击 “开始AI声音克隆吧” 报错，提示 “TypeError: Invalid file: None”
